name: fusebox

on: [push, pull_request]

jobs:
  clojure-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Clojure
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          tools-deps: 'latest'
          cli: 'latest'

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}

      - name: Run Clojure tests
        run: clojure -M:dev:test

  clojurescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-clojure-${{ hashFiles('**/shadow-cljs.edn') }}

      - name: Install shadow-cljs
        run: npm install shadow-cljs

      - name: Run ClojureScript tests
        run: npx shadow-cljs compile node-test
